name: test-configure
base: core18
version: '0.1'
summary: Demo some configure hook
description: |
  Demo some snap confure hook bits.

grade: devel
confinement: strict

apps:
  get:
    command: configs

parts:
  get:
    plugin: dump
    source: get
